# Config for ZaniPortals

PortalStructure:
    # The blocks that the link signs can be placed on.
    SignPlaceOnBlocks:
        - 49
    
    # The other blocks in the frame
    PortalFrameBlocks:
        - 49
        - 112
    
    # This must be a transparent block or people won't be able to enter it.
    PortalBlock: 9
    
    # The maximum number of blocks that the portal volume can take up.
    # Also is the maxiumum number of frame blocks, but that will usually be less anyways.
    MaxPortalBlocks: 150
    