name: ZaniPortals
main: com.treyzania.mc.zaniportals.ZaniPortalsBukkit
author: treyzania
version: '0.0.1'
commands:
    listportals:
        aliases: [portals]
        description: Lists all the portals on the server.
        usage: /portals
    giveportalactivator:
        aliases: [giveactivator]
        description: Gives a portal activator to the specifcied player.
        usage: /giveportalactivator <player> [qty]