name: ZaniPortals
main: com.treyzania.mc.zaniportals.ZaniPortalsBukkit
author: treyzania
version: '0.0.1'
commands:
    listportals:
        aliases: [portals]
        description: Lists all the portals on the server.
        usage: /portals
    giveportalactivator:
        aliases: [giveactivator]
        description: Gives a portal activator to the specifcied player.
        usage: /giveportalactivator <player> [qty]
    giveplayerlinkpearl:
        aliases: [giveplayerpearl, playerpearl]
        description: Gives the user a link pearl that teleports subjects to a player, if online.
        usage: /giveplayerpearl <UUID | online player name> [qty]
    setportalaccess:
        aliases: [pacc]
        description: Sets who can get a link item from a portal.
        usage: /setportalaccess <portal name> <self|all>