package com.treyzania.mc.zaniportals;

public class Point3i implements Comparable<Point3i> {
	
	public final int x, y, z;
	
	public Point3i(int x, int y, int z) {
		
		this.x = x;
		this.y = y;
		this.z = z;
		
	}
	
	@Override
	public String toString() {
		return String.format("int(%s,%s,%s)", this.x, this.y, this.z);
	}
	
	@Override
	public int hashCode() {
		
		// Autogenerated yuck.
		
		final int prime = 31;
		int result = 1;
		result = prime * result + x;
		result = prime * result + y;
		result = prime * result + z;
		return result;
		
	}
	
	@Override
	public boolean equals(Object obj) {
		
		// Autogenerated yuck.
		
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Point3i other = (Point3i) obj;
		if (x != other.x)
			return false;
		if (y != other.y)
			return false;
		if (z != other.z)
			return false;
		return true;
		
	}

	@Override
	public int compareTo(Point3i o) {
		
		if (o == null) throw new NullPointerException("Can't compare with a null object!");
		
		// Big yucky tree.
		if (this.x > o.x) {
			return 1;
		} else if (this.x < o.x) {
			return -1;
		} else {
			
			if (this.y > o.y) {
				return 1;
			} else if (this.y < o.y) {
				return -1;
			} else {
				
				if (this.z > o.z) {
					return 1;
				} else if (this.z < o.z) {
					return -1;
				} else {
					return 0;
				}
				
			}
			
		}
		
	}
	
}
